/**
 * Identifiers are UUIDv7 strings generated by the application, so an aggregate can be built
 * without touching the database. The aliases carry no validation: shape is checked once, at the
 * boundary, and a domain that re-validated every string would be checking the wrong thing twice.
 * What they buy is readable signatures — `record(craId, missionId)` cannot be called backwards
 * without the reader seeing it.
 */
export type CraId = string;
/** A person of the firm. A manager is one too, which is why validation is typed with this one. */
export type ConsultantId = string;
export type MissionId = string;
/** A certification-backed clearance (`CONTEXT.md` § Habilitation), e.g. PASSI. */
export type HabilitationId = string;
export type OfficeId = string;
