import {
  type EventHandler,
  lastDayOf,
  periodFromIso,
  type TimesheetValidated,
} from '@erp/platform';

import type { Client } from '../domain/client.ts';
import type { DeclinedDays } from '../domain/declined-days.ts';
import type { ClientId, InvoiceId, MissionId } from '../domain/ids.ts';
import { type InvoiceLine, regieLine } from '../domain/invoice-line.ts';
import { billedParty, Invoice } from '../domain/invoice.ts';
import type { LegalMentions } from '../domain/mentions.ts';
import type { PaymentTerms } from '../domain/payment-terms.ts';
import type { BillingReference } from '../domain/reference.ts';
import type { LegalEntity } from '../domain/seller.ts';
import { resolveVat } from '../domain/vat.ts';

/**
 * `billing` reacting to `timesheet.TimesheetValidated`, and the whole point of the boundary: there
 * is no import of `timesheet` in this file, in this package, or in its tests — the dependency
 * rule forbids one, so a test that wanted to build the event from the real aggregate could not.
 * What arrives is the contract in `@erp/platform` and nothing else.
 *
 * Drafting is a pure function of the event and the reference snapshot. It performs no I/O, which
 * is the property ADR-0001 requires of a subscriber running inside the emitter's transaction.
 */

export interface DraftInvoicesResult {
  /** One per client, because one validated Cra can span missions sold to different clients. */
  readonly invoices: readonly Invoice[];
  readonly declined: readonly DeclinedDays[];
}

export interface DraftInvoicesDependencies {
  readonly reference: BillingReference;
  readonly seller: LegalEntity;
  readonly terms: PaymentTerms;
  readonly mentions: LegalMentions;
  /** UUIDv7, generated by the application so a document exists before any database does. */
  readonly newInvoiceId: () => InvoiceId;
  /** What the line says it is for. Composed here: document content is not screen labelling. */
  readonly designation: (input: { missionId: MissionId; period: string }) => string;
}

export function draftInvoicesFrom(
  dependencies: DraftInvoicesDependencies,
  event: TimesheetValidated,
): DraftInvoicesResult {
  const { payload } = event;
  const period = periodFromIso(payload.period);
  // Both dated references resolve at the close of the period the work covers — one rule, one
  // mechanism, for the Tjm and for the VAT rate alike (ADR-0017, ADR-0034).
  const on = lastDayOf(period);

  // Keyed by client and holding the client: one validated Cra can span missions sold to two
  // different clients, and two clients are two invoices.
  const perClient = new Map<ClientId, { client: Client; lines: InvoiceLine[] }>();
  const declined: DeclinedDays[] = [];

  for (const worked of payload.missions) {
    const mission = dependencies.reference.mission(worked.missionId);
    if (mission === null) {
      declined.push({ ...worked, reason: 'unknownMission' });
      continue;
    }
    if (mission.billingModel !== 'Regie') {
      declined.push({ ...worked, reason: 'notRegie' });
      continue;
    }

    const tjmCents = dependencies.reference.tjmCentsOn(mission.id, on);
    if (tjmCents === null) {
      declined.push({ ...worked, reason: 'noAgreedRate' });
      continue;
    }

    const client = dependencies.reference.client(mission.clientId);
    if (client === null) {
      declined.push({ ...worked, reason: 'unknownClient' });
      continue;
    }

    const bucket = perClient.get(client.id) ?? { client, lines: [] };
    bucket.lines.push(
      regieLine({
        designation: dependencies.designation({
          missionId: mission.id,
          period: payload.period,
        }),
        missionId: mission.id,
        craId: payload.craId,
        period: payload.period,
        halfDays: worked.halfDays,
        tjmCents,
        vat: resolveVat({ serviceNature: 'consultingService', client, on }),
      }),
    );
    perClient.set(client.id, bucket);
  }

  const invoices = [...perClient]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([, bucket]) =>
      Invoice.draft({
        id: dependencies.newInvoiceId(),
        officeId: payload.officeId,
        seller: dependencies.seller,
        billedTo: billedParty(bucket.client),
        supplyPeriod: period,
        lines: bucket.lines,
        terms: dependencies.terms,
        mentions: dependencies.mentions,
        validatedBy: [payload.validatedBy],
      }),
    );

  return { invoices, declined };
}

/**
 * Subscribes `billing` to the fact `timesheet` publishes. The handler performs no I/O: it drafts
 * and hands the result to the caller, which is what lets it run inside the emitter's transaction
 * (ADR-0001). The day it needs to write, an outbox is required — that is the threshold.
 */
export function onTimesheetValidated(
  dependencies: DraftInvoicesDependencies,
  drafted: (result: DraftInvoicesResult, event: TimesheetValidated) => void,
): EventHandler<TimesheetValidated> {
  return (event) => {
    drafted(draftInvoicesFrom(dependencies, event), event);

    return Promise.resolve();
  };
}
