import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import importX from 'eslint-plugin-import-x';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

// Module boundaries are NOT here: dependency-cruiser owns them, so a violation fails its own
// CI job instead of hiding inside a lint run. See docs/adr/0001.

// `no-restricted-syntax` does not merge across config blocks — a later block replaces the whole
// list. Hence the constant, re-injected on both sides.
const NATIVE_ERROR_CTORS =
  '/^(Error|TypeError|RangeError|SyntaxError|ReferenceError|EvalError|URIError|AggregateError)$/';
// The wall clock, not the `Date` constructor. Domain code may not read time at all (the block
// below forbids both forms); a TEST may build a fixed instant — that is what a fake clock is —
// but reading `new Date()` or `Date.now()` in one makes the assertion depend on the day it runs.
const NO_WALL_CLOCK = [
  {
    selector: 'NewExpression[callee.name="Date"][arguments.length=0]',
    message:
      'No `new Date()` without an argument: a test that reads the wall clock passes today and fails on 29 February. Build a fixed instant.',
  },
  {
    selector: 'MemberExpression[object.name="Date"][property.name="now"]',
    message: 'No `Date.now()` in a test: build a fixed instant instead.',
  },
];

// Float-producing arithmetic on money. `BUILD-RULES.md` § Money has claimed this rule in the
// present tense since Phase 0 and nothing implemented it; ADR-0035 decides what it bans and what
// replaces each ban. Split in two because the two halves have different scopes: the calls are
// wrong in a test as well (a `Math.round` added to make an assertion pass is the failure itself),
// while a decimal literal is how a negative test hands a float to the factory that refuses it.
const NO_FLOAT_MONEY_CALLS = [
  {
    selector:
      'CallExpression[callee.name="parseFloat"], MemberExpression[object.name="Number"][property.name="parseFloat"]',
    message:
      'No `parseFloat`: a monetary value is an integer number of cents (ADR-0002). Parsing a decimal string is how a float gets in.',
  },
  {
    selector: 'CallExpression[callee.name="Number"]',
    message:
      'No `Number()`: it turns a decimal string into a float without saying so. `Number.parseInt` on an integer string is allowed and says which it is.',
  },
  {
    selector: 'MemberExpression[object.name="Math"][property.name=/^(round|fround)$/]',
    message:
      'No `Math.round`: it recovers from a float that should never have existed. Round half-up on integers, at the call site that asserts its precondition (ADR-0035).',
  },
];

const NO_DECIMAL_LITERAL = [
  {
    // Two forms, because a float does not need a dot: `85e-3` is 0.085, which is the exact value
    // ADR-0035 was written about, and a selector anchored on the dot cannot see it.
    selector: 'Literal[raw=/^[0-9]*\\.[0-9]/], Literal[raw=/^[0-9][0-9_]*[eE]-/]',
    message:
      'No decimal literal in the domain: an amount is cents, a rate is basis points, a quantity is half-days. A float literal is a unit escaping its type (ADR-0002, ADR-0035).',
  },
];

const NO_BARE_ERROR = [
  {
    selector: `ThrowStatement > :matches(NewExpression, CallExpression)[callee.name=${NATIVE_ERROR_CTORS}]`,
    message:
      'Throw a typed error: a business error (expected, part of the contract) or a technical failure (retryable). Never a bare `new Error()`.',
  },
];

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/.next/**',
      '**/*.d.ts',
      // Stryker's own working directory and HTML report (ADR-0027, Phase 7): instrumented
      // mutant copies and generated markup, neither of which is code this repository wrote.
      '.stryker-tmp/**',
      'reports/**',
      // Deliberate boundary violation, excluded from tsconfig. dependency-cruiser reads it.
      '**/__boundary-fixture__/**',
      // Generated by the TanStack Router Vite plugin on every `dev`/`build` (ADR-0062, Phase 4):
      // its own header says "you should also exclude this file from your linter". A narrow,
      // single-path ignore rather than a directory glob — `apps/web/src/routes/**` (hand-written)
      // stays linted in full.
      'apps/web/src/routeTree.gen.ts',
    ],
  },

  js.configs.recommended,

  // `projectService` is required: without it the type-aware rules below silently report nothing
  // while the config still looks like it enforces them.
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.node },
      parserOptions: {
        projectService: { allowDefaultProject: ['*.js', '*.mjs', '*.cjs'] },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    linterOptions: { reportUnusedDisableDirectives: 'error' },
    settings: {
      'import-x/resolver': {
        typescript: {
          alwaysTryTypes: true,
          // `apps/api/tsconfig.json` was never in this list either, and its absence is not
          // repeated here on purpose: `apps/web` needs its own project registered so the
          // resolver can follow the `@/` alias (`apps/web/tsconfig.json`'s `paths`), and
          // `apps/api` picks up the same fix at no extra cost.
          project: [
            'tsconfig.json',
            'packages/*/tsconfig.json',
            'apps/api/tsconfig.json',
            'apps/web/tsconfig.json',
          ],
          noWarnOnMultipleProjects: true,
        },
      },
    },
  },

  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: { 'import-x': importX },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        { assertionStyle: 'as', objectLiteralTypeAssertions: 'never' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-import-type-side-effects': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/only-throw-error': 'error',
      // The three call bans are repository-wide, which is how BUILD-RULES § Money states them and
      // is not how they were first written: scoped to `domain/`, they exempted `application/` —
      // the layer that reads a rate off the reference and hands it to a line. That is the failure
      // family the boundary rules already name, one directory down. The decimal-LITERAL ban stays
      // narrow, in the block below, for the reason ADR-0035 gives.
      'no-restricted-syntax': ['error', ...NO_BARE_ERROR, ...NO_FLOAT_MONEY_CALLS],

      // Not in strictTypeChecked: a missing `case` on a union has to break the build.
      '@typescript-eslint/switch-exhaustiveness-check': 'error',

      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/return-await': ['error', 'in-try-catch'],

      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'error',
      'no-param-reassign': ['error', { props: true, ignorePropertyModificationsFor: ['acc'] }],
      'prefer-const': 'error',

      'import-x/no-extraneous-dependencies': [
        'error',
        {
          devDependencies: [
            '**/*.test.ts',
            '**/*.int.test.ts',
            '**/testing/**',
            '**/*.config.ts',
            'eslint.config.js',
            // Playwright specs: e2e code that is never shipped, same reasoning as `testing/**`.
            'apps/web/e2e/**',
          ],
        },
      ],
      'import-x/no-cycle': ['error', { maxDepth: Infinity }],
      'import-x/no-default-export': 'error',
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          pathGroups: [{ pattern: '@erp/**', group: 'internal', position: 'before' }],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
    },
  },

  {
    // `apps/web` (ADR-0062, frontend-plan.md Phase 1.3). Browser globals: the base block above
    // sets only `globals.node`, and flat config merges `languageOptions.globals` across cascading
    // blocks rather than replacing it, so this adds `document`/`window`/… without losing `process`
    // et al. in `vite.config.ts`/`playwright.config.ts`. `no-restricted-syntax` is deliberately
    // NOT set here: the rule does not merge across config blocks (see the comment on
    // `NATIVE_ERROR_CTORS` above), and setting it here would silently drop `NO_BARE_ERROR` +
    // `NO_FLOAT_MONEY_CALLS` for every file this block matches — the base `**/*.ts`/`**/*.tsx`
    // block already carries both and this block inherits them unchanged.
    files: ['apps/web/**/*.ts', 'apps/web/**/*.tsx'],
    ...reactHooks.configs.flat.recommended,
    languageOptions: {
      globals: { ...globals.browser },
    },
  },

  {
    // `reactHooks.configs.flat.recommended` is the first config in this repository to ship rules
    // at `warn`: `exhaustive-deps`, `incompatible-library`, `unsupported-syntax`. CLAUDE.md holds
    // that a rule left at `warn` severity is not a gate, and `pnpm run lint` now carries
    // `--max-warnings=0` so that stays mechanically true. These three are raised here as well,
    // and not left to the flag alone: the flag makes a warning fail the run, this makes the
    // failure name a rule that was decided rather than a threshold that was crossed.
    files: ['apps/web/**/*.ts', 'apps/web/**/*.tsx'],
    rules: {
      'react-hooks/exhaustive-deps': 'error',
      'react-hooks/incompatible-library': 'error',
      'react-hooks/unsupported-syntax': 'error',
    },
  },

  {
    // The kernel is in this list for the reason ADR-0033 gives: it holds domain-grade code and
    // has no `domain/` directory to be matched by the first glob.
    files: ['packages/*/src/domain/**/*.ts', 'packages/platform/src/**/*.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        ...NO_BARE_ERROR,
        ...NO_FLOAT_MONEY_CALLS,
        ...NO_DECIMAL_LITERAL,
        {
          selector: 'NewExpression[callee.name="Date"]',
          message: 'No `new Date()` in the domain: time comes from the injected `Clock` port.',
        },
        {
          selector: 'MemberExpression[object.name="Date"][property.name="now"]',
          message: 'No `Date.now()` in the domain: use the injected `Clock` port.',
        },
        {
          selector: 'MethodDefinition[kind="set"]',
          message:
            'No public setter: an object must not be able to exist in an invalid state. Invariants belong in the factory or the constructor.',
        },
      ],
    },
  },

  {
    // Shared fixtures, and NOT tests. BUILD-RULES justifies the test exemption on "it is not
    // shipped"; a `testing/` file is in its package's tsconfig, compiles to `dist`, and — since
    // Phase 2 — is where every seeded `tjmCents` in `billing` is written. It therefore keeps the
    // domain list, with the single narrowing a fixture actually needs: a fake clock is built from
    // a literal instant, so the absolute `new Date(...)` ban becomes the wall-clock ban.
    files: ['**/testing/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      'no-restricted-syntax': [
        'error',
        ...NO_BARE_ERROR,
        ...NO_WALL_CLOCK,
        ...NO_FLOAT_MONEY_CALLS,
        ...NO_DECIMAL_LITERAL,
        {
          selector: 'MethodDefinition[kind="set"]',
          message:
            'No public setter: an object must not be able to exist in an invalid state. Invariants belong in the factory or the constructor.',
        },
      ],
      'import-x/no-extraneous-dependencies': ['error', { devDependencies: true }],
    },
  },

  {
    files: ['**/*.test.ts', '**/*.int.test.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      // Replaces the domain block's list for test files — `no-restricted-syntax` does not merge.
      // A fake clock is built from a literal instant, so the absolute ban on `new Date(...)` is
      // narrowed here to the wall clock, and the ban on bare errors is re-injected unchanged.
      // Same shape for money: the calls stay banned, the decimal LITERAL does not — a negative
      // test proves a factory refuses a float by handing it one, and `halfDays(1.5)` is that test.
      'no-restricted-syntax': [
        'error',
        ...NO_BARE_ERROR,
        ...NO_WALL_CLOCK,
        ...NO_FLOAT_MONEY_CALLS,
      ],
      // No `packageDir`: each test is judged against the package.json of ITS OWN package, so a
      // domain test importing an ORM fails here.
      'import-x/no-extraneous-dependencies': ['error', { devDependencies: true }],
    },
  },

  {
    files: ['**/*.config.ts', '**/*.config.js', '**/*.cjs', 'eslint.config.js'],
    rules: {
      'import-x/no-default-export': 'off',
      'no-restricted-syntax': 'off',
    },
  },

  {
    // The console IS the expected output of repository tooling.
    files: ['scripts/**/*.ts'],
    rules: { 'no-console': 'off' },
  },

  {
    // Infrastructure adapters: persistence code that talks to Postgres. `@types/pg` is a
    // devDependency (types are compile-time, not runtime), `query<T>` is the standard pg client
    // pattern, and BIGINT columns return strings that must become numbers. `NO_FLOAT_MONEY_CALLS`
    // already permits the integer-only subset — its `Number()` selector matches a bare call and
    // not `Number.parseInt`, which names what it does — so this block keeps it. It was dropped
    // here when the block was written, which switched `parseFloat`, `Number()` and `Math.round`
    // back on in the one layer that reads money out of the database: the failure family the
    // `application/` scope fix already named, one directory further out. `tests/lint-rules.test.ts`
    // holds the negative test.
    files: ['packages/*/src/infrastructure/**/*.ts', 'apps/*/src/persistence/**/*.ts'],
    ignores: ['**/*.test.ts', '**/*.int.test.ts'],
    rules: {
      '@typescript-eslint/no-unnecessary-type-parameters': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      'no-restricted-syntax': [
        'error',
        ...NO_BARE_ERROR,
        ...NO_WALL_CLOCK,
        ...NO_FLOAT_MONEY_CALLS,
      ],
    },
  },

  {
    // Test harness: infrastructure that hooks into Vitest and manages connections. The
    // devDependencies restriction does not apply — it is not shipped. The **bare-error ban does**,
    // and it was dropped here when this block was written: that made `tests/harness/` the only
    // place in the repository where `throw new Error()` was legal, including for `PgEventStore`,
    // which ADR-0020 says is promoted to `apps/api/` in Phase 5. Its errors are typed by
    // `errors.ts`, which is local on purpose — the harness carries no workspace dependency.
    files: ['tests/harness/**/*.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        ...NO_BARE_ERROR,
        ...NO_WALL_CLOCK,
        ...NO_FLOAT_MONEY_CALLS,
      ],
      'import-x/no-extraneous-dependencies': ['error', { devDependencies: true }],
    },
  },

  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    extends: [tseslint.configs.disableTypeChecked],
  },

  {
    // dependency-cruiser loads its config through require().
    files: ['**/*.cjs'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },

  // Always last: neutralises anything that would fight Prettier.
  prettier,
);
