/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellPreFacturierRouteImport } from './routes/_shell/pre-facturier'
import { Route as ShellTableauDeBordRouteImport } from './routes/_shell/tableau-de-bord'
import { Route as DevComposantsRouteImport } from './routes/dev.composants'
import { Route as ShellCraIndexRouteImport } from './routes/_shell/cra.index'
import { Route as ShellCraPeriodRouteImport } from './routes/_shell/cra.$period'
import { Route as ShellFacturesIndexRouteImport } from './routes/_shell/factures.index'
import { Route as ShellFacturesIdRouteImport } from './routes/_shell/factures.$id'
import { Route as ShellMargeIndexRouteImport } from './routes/_shell/marge.index'
import { Route as ShellMargeConsultantIdRouteImport } from './routes/_shell/marge.$consultantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellPreFacturierRoute = ShellPreFacturierRouteImport.update({
  id: '/pre-facturier',
  path: '/pre-facturier',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTableauDeBordRoute = ShellTableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => ShellRoute,
} as any)
const DevComposantsRoute = DevComposantsRouteImport.update({
  id: '/dev/composants',
  path: '/dev/composants',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCraIndexRoute = ShellCraIndexRouteImport.update({
  id: '/cra/',
  path: '/cra/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCraPeriodRoute = ShellCraPeriodRouteImport.update({
  id: '/cra/$period',
  path: '/cra/$period',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFacturesIndexRoute = ShellFacturesIndexRouteImport.update({
  id: '/factures/',
  path: '/factures/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFacturesIdRoute = ShellFacturesIdRouteImport.update({
  id: '/factures/$id',
  path: '/factures/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMargeIndexRoute = ShellMargeIndexRouteImport.update({
  id: '/marge/',
  path: '/marge/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMargeConsultantIdRoute = ShellMargeConsultantIdRouteImport.update({
  id: '/marge/$consultantId',
  path: '/marge/$consultantId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pre-facturier': typeof ShellPreFacturierRoute
  '/tableau-de-bord': typeof ShellTableauDeBordRoute
  '/dev/composants': typeof DevComposantsRoute
  '/cra/$period': typeof ShellCraPeriodRoute
  '/factures/$id': typeof ShellFacturesIdRoute
  '/marge/$consultantId': typeof ShellMargeConsultantIdRoute
  '/cra/': typeof ShellCraIndexRoute
  '/factures/': typeof ShellFacturesIndexRoute
  '/marge/': typeof ShellMargeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pre-facturier': typeof ShellPreFacturierRoute
  '/tableau-de-bord': typeof ShellTableauDeBordRoute
  '/dev/composants': typeof DevComposantsRoute
  '/cra/$period': typeof ShellCraPeriodRoute
  '/factures/$id': typeof ShellFacturesIdRoute
  '/marge/$consultantId': typeof ShellMargeConsultantIdRoute
  '/cra': typeof ShellCraIndexRoute
  '/factures': typeof ShellFacturesIndexRoute
  '/marge': typeof ShellMargeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/pre-facturier': typeof ShellPreFacturierRoute
  '/_shell/tableau-de-bord': typeof ShellTableauDeBordRoute
  '/dev/composants': typeof DevComposantsRoute
  '/_shell/cra/$period': typeof ShellCraPeriodRoute
  '/_shell/factures/$id': typeof ShellFacturesIdRoute
  '/_shell/marge/$consultantId': typeof ShellMargeConsultantIdRoute
  '/_shell/cra/': typeof ShellCraIndexRoute
  '/_shell/factures/': typeof ShellFacturesIndexRoute
  '/_shell/marge/': typeof ShellMargeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pre-facturier'
    | '/tableau-de-bord'
    | '/dev/composants'
    | '/cra/$period'
    | '/factures/$id'
    | '/marge/$consultantId'
    | '/cra/'
    | '/factures/'
    | '/marge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pre-facturier'
    | '/tableau-de-bord'
    | '/dev/composants'
    | '/cra/$period'
    | '/factures/$id'
    | '/marge/$consultantId'
    | '/cra'
    | '/factures'
    | '/marge'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/pre-facturier'
    | '/_shell/tableau-de-bord'
    | '/dev/composants'
    | '/_shell/cra/$period'
    | '/_shell/factures/$id'
    | '/_shell/marge/$consultantId'
    | '/_shell/cra/'
    | '/_shell/factures/'
    | '/_shell/marge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  DevComposantsRoute: typeof DevComposantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/pre-facturier': {
      id: '/_shell/pre-facturier'
      path: '/pre-facturier'
      fullPath: '/pre-facturier'
      preLoaderRoute: typeof ShellPreFacturierRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tableau-de-bord': {
      id: '/_shell/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof ShellTableauDeBordRouteImport
      parentRoute: typeof ShellRoute
    }
    '/dev/composants': {
      id: '/dev/composants'
      path: '/dev/composants'
      fullPath: '/dev/composants'
      preLoaderRoute: typeof DevComposantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/cra/': {
      id: '/_shell/cra/'
      path: '/cra'
      fullPath: '/cra/'
      preLoaderRoute: typeof ShellCraIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cra/$period': {
      id: '/_shell/cra/$period'
      path: '/cra/$period'
      fullPath: '/cra/$period'
      preLoaderRoute: typeof ShellCraPeriodRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/factures/': {
      id: '/_shell/factures/'
      path: '/factures'
      fullPath: '/factures/'
      preLoaderRoute: typeof ShellFacturesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/factures/$id': {
      id: '/_shell/factures/$id'
      path: '/factures/$id'
      fullPath: '/factures/$id'
      preLoaderRoute: typeof ShellFacturesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/marge/': {
      id: '/_shell/marge/'
      path: '/marge'
      fullPath: '/marge/'
      preLoaderRoute: typeof ShellMargeIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/marge/$consultantId': {
      id: '/_shell/marge/$consultantId'
      path: '/marge/$consultantId'
      fullPath: '/marge/$consultantId'
      preLoaderRoute: typeof ShellMargeConsultantIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellPreFacturierRoute: typeof ShellPreFacturierRoute
  ShellTableauDeBordRoute: typeof ShellTableauDeBordRoute
  ShellCraPeriodRoute: typeof ShellCraPeriodRoute
  ShellFacturesIdRoute: typeof ShellFacturesIdRoute
  ShellMargeConsultantIdRoute: typeof ShellMargeConsultantIdRoute
  ShellCraIndexRoute: typeof ShellCraIndexRoute
  ShellFacturesIndexRoute: typeof ShellFacturesIndexRoute
  ShellMargeIndexRoute: typeof ShellMargeIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellPreFacturierRoute: ShellPreFacturierRoute,
  ShellTableauDeBordRoute: ShellTableauDeBordRoute,
  ShellCraPeriodRoute: ShellCraPeriodRoute,
  ShellFacturesIdRoute: ShellFacturesIdRoute,
  ShellMargeConsultantIdRoute: ShellMargeConsultantIdRoute,
  ShellCraIndexRoute: ShellCraIndexRoute,
  ShellFacturesIndexRoute: ShellFacturesIndexRoute,
  ShellMargeIndexRoute: ShellMargeIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  DevComposantsRoute: DevComposantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
