/**
 * Identifiers are UUIDv7 strings generated by the application, so a document can be built without
 * touching the database. As in `timesheet`, the aliases carry no validation — shape is checked
 * once, at the boundary — and what they buy is a signature a reader cannot call backwards.
 *
 * `MissionId`, `ConsultantId` and `OfficeId` are declared again here rather than imported: they
 * are the same UUIDs, written by the same seed (ADR-0031), and the import that would share the
 * alias is the import the boundary forbids. The duplication is the shape of the rule.
 */
export type InvoiceId = string;
export type ClientId = string;
export type MissionId = string;
export type ConsultantId = string;
export type OfficeId = string;
